<?php

namespace AppBundle\Repository;

/**
 * entidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entidadRepository extends \Doctrine\ORM\EntityRepository
{
}
